# This configuration is for teaching kustomize how to update name ref and var substitution 
nameReference:
- kind: ConfigMap
  group: ""
  fieldSpecs:
  - kind: Deployment
    group: apps
    path: spec/template/spec/containers/envFrom/configMapKeyRef/name
