kind: Cluster
apiVersion: clusterregistry.k8s.io/v1alpha1
metadata:
  namespace: mig
  name: local-cluster
spec:
  kubernetesApiEndpoints:
    serverEndpoints:
      - clientCIDR: "0.0.0.0"
        serverAddress: "https://my-local-cluster-ip.nip.io:8443"
