apiVersion: migration.openshift.io/v1alpha1
kind: MigAssetCollection
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migassets-sample
  namespace: mig
spec:
  # [!] Change namespaces to contain the list of namespaces that should be migrated
  namespaces: ['nginx-example']

