apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migstorage-sample
  namespace: mig
spec:
  backupStorageProvider: aws
  volumeSnapshotProvider: aws
  
  backupStorageConfig:
    awsBucketName: foo
    awsRegion: foo
    credsSecretRef:
      namespace: mig
      name: migstorage-creds
    #awsKmsKeyId: foo
    #awsPublicUrl: foo
    #awsSignatureVersion: "4"

  volumeSnapshotConfig:
    awsRegion: foo
    credsSecretRef:
      namespace: mig
      name: migstorage-creds

