apiVersion: migration.openshift.io/v1alpha1
kind: MigMigration
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migmigration-sample
  namespace: mig
spec:
  stage: false
  migPlanRef:
    name: migplan-sample
    namespace: mig

