apiVersion: migration.openshift.io/v1alpha1
kind: MigStage
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migstage-sample
  namespace: mig
spec:

  migPlanRef:
    name: migplan-sample
    namespace: mig
