apiVersion: migration.openshift.io/v1alpha1
kind: MigStorage
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: migstorage-sample
  namespace: mig
spec:
  backupStorageProvider: aws
  volumeSnapshotProvider: aws
  backupStorageConfig:
    awsBucketName: foo
    awsKmsKeyId: foo
    awsPublicUrl: foo
    awsRegion: foo
    awsSignatureVersion: "4"
    credsSecretRef:
      namespace: mig
      name: cloud-creds
  volumeSnapshotConfig:
    awsRegion: foo
    credsSecretRef:
      namespace: mig
      name: cloud-creds

