apiVersion: v1
kind: Secret
metadata:
  name: sa-token-remote
  namespace: mig
type: Opaque
data:
  # [!] Change saToken to contain a base64 encoded SA token with cluster-admin privileges on the remote (AWS) cluster
  saToken: <your-base64-encoded-aws-sa-token-here>
